Repository streetcatshelter/disCATch_Client, pull requests merged in 2022-03, with the labels that each got.

#410 [수임] :lipstick: resetCss 추가
  README.md
  discatch/src/reset.css
Labels: style

#413 ♻️ 커뮤니티 작성 페이지와 커뮤니티 수정 페이지 병합
  discatch/src/components/Router.js
  discatch/src/components/community/CommunityPreview.jsx
  discatch/src/components/templates/Template.jsx
  discatch/src/pages/community/CommunityPostEdit.jsx
  discatch/src/pages/community/CommunityPostWriteEdit.jsx
  discatch/src/pages/index.js
  discatch/src/redux/modules/community.jsx
Labels: refac

#414 [수임] 🎨 전체컴포넌트에 themeProvider 설정 / 캘린더 스타일 컴포넌트 분리 및 중복 로직 수정
  discatch/src/components/calendar/Calendar.jsx
  discatch/src/components/calendar/Calendar.styled.jsx
  discatch/src/components/calendar/CalendarBody.jsx
  discatch/src/components/calendar/CalendarDates.jsx
  discatch/src/components/calendar/CalendarHead.jsx
  discatch/src/components/calendar/CalendarModal.jsx
  discatch/src/components/catPosts/CatCalendar.jsx
  discatch/src/components/index.js
  discatch/src/index.jsx
  discatch/src/pages/cat/CatDetail.jsx
  discatch/src/styles/theme.js
Labels: style, refac

#415 [수임] ♻️ 캘린더 중복코드 정리 및 스타일링 변경/🔥 알람 관련 컴포넌트 삭제/📝 const 추가
  discatch/src/components/alram/EventAlram.jsx
  discatch/src/components/calendar/Calendar.jsx
  discatch/src/components/calendar/Calendar.styled.jsx
  discatch/src/components/calendar/CalendarDates.jsx
  discatch/src/components/calendar/CalendarHead.jsx
  discatch/src/components/calendar/CalendarModal.jsx
  discatch/src/components/index.js
  discatch/src/consts/constances.js
Labels: style, refac

#416 [진우] ♻️ Route를 PrivateRoute와 PublicRoute로 분리
  discatch/src/components/Router.js
  discatch/src/components/route/PrivateRoute.jsx
  discatch/src/components/route/PublicRoute.jsx
Labels: refac

#419 [수임] :art: moment 불변성 문제로 인해 date함수로 util함수 구현 및 moment 삭제
  discatch/package.json
  discatch/src/components/catPosts/Diary.jsx
  discatch/src/components/chat/ChatMessage.jsx
  discatch/src/components/comment/CommentCard.jsx
  discatch/src/components/community/CommunityPost.jsx
  discatch/src/components/myPage/MyPageCatPost.jsx
  discatch/src/components/myPage/Notice.jsx
  discatch/src/components/myPage/NoticeDesc.jsx
  discatch/src/components/templates/ContentHeader.jsx
  discatch/src/pages/chat/ChatMainPage.jsx
  discatch/src/pages/chat/ChatRoomPage.jsx
  discatch/src/pages/mypage/RandomUserProfile.jsx
  discatch/src/utils/checkedOverDay.js
  discatch/src/utils/dateFormat.js
  discatch/src/utils/index.js
  discatch/src/utils/tensDigit.js
  discatch/src/utils/timeForToday.js
  discatch/yarn.lock
Labels: refac

#420 [진우] ♻️ 동네 정보 확인 util 함수 구현
  discatch/package-lock.json
  discatch/src/pages/cat/CatDetail.jsx
  discatch/src/pages/cat/CatDetailInfo.jsx
  discatch/src/pages/cat/CatInfoWrite.jsx
  discatch/src/pages/cat/Home.jsx
  discatch/src/utils/locationCheck.js
Labels: refac

#422 ♻️ 동네 정보 확인 util 함수 구현
  discatch/src/pages/cat/CatDetail.jsx
  discatch/src/pages/cat/CatDetailInfo.jsx
  discatch/src/pages/cat/CatInfoWrite.jsx
  discatch/src/pages/cat/Home.jsx
  discatch/src/utils/locationCheck.js
Labels: refac

#425 [진우] ♻️ Router 관련 오류 해결
  discatch/src/components/Router.js
Labels: bug

#428 [수임] ♻️ 코멘트 관련 컴포넌트 스타일 분리 및 코드정리 / textarea element 수정
  discatch/package.json
  discatch/src/components/calendar/Calendar.jsx
  discatch/src/components/calendar/Calendar.styled.jsx
  discatch/src/components/calendar/CalendarHead.jsx
  discatch/src/components/calendar/CalendarModal.jsx
  discatch/src/components/catPosts/catDiary/CatDiary.jsx
  discatch/src/components/catPosts/catPost/CatPost.Styled.jsx
  discatch/src/components/catPosts/catPost/CatPost.jsx
  discatch/src/components/comment/Comment.jsx
  discatch/src/components/comment/CommentList.jsx
  discatch/src/components/comment/commentCard/CommentCard.jsx
  discatch/src/components/comment/commentCard/CommentCard.styled.jsx
  discatch/src/components/comment/commentHead/Comment.styled.jsx
  discatch/src/components/comment/commentHead/CommentHead.jsx
  discatch/src/components/index.js
  discatch/src/elements/TextArea.jsx
  discatch/src/utils/index.js
  discatch/src/utils/textareaHeightHandler.js
  discatch/yarn.lock
Labels: refac

#429 [수임] ♻️ 카카오맵 코드 정리
  discatch/src/components/chat/ChatMain.jsx
  discatch/src/components/map/Location.jsx
  discatch/src/components/map/Location.styled.jsx
  discatch/src/components/map/MakeMarker.jsx
  discatch/src/components/map/MapModal.jsx
  discatch/src/components/map/SearchPlace.jsx
  discatch/src/components/map/ShowCat.jsx
  discatch/src/elements/Button.jsx
  discatch/src/utils/index.js
  discatch/src/utils/makeKaKaoMap.js
Labels: refac
